name: Elixir CI

on:
  push:
    paths:
    - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Just a label for the Docker container
      db:
        # Docker image
        image: postgres:12
        ports: ['5432:5432']
        env:
          # Password for the test database
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get --only test
      working-directory: ./backend
    - name: Run Unit Tests
      run: mix test
      working-directory: ./backend
