name: Elixir CI

on:
  push:
    paths:
    - 'backend/**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Change Directory to Backend
      run: cd backend
    - name: Install Dependencies
      run: mix deps.get
    - name: Test Compilation
      run: mix compile
    - name: Test Migrations
      run: mix ecto.migrate
    # - name: Run Unit Tests
    #   run: mix test
