# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    paths:
    - frontend/**

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - 8.x

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
      working-directory: ./frontend
      
    - run: npm run build --if-present
      working-directory: ./frontend
      
    - run: npm test
      working-directory: ./frontend
      env:
        CI: true
