name: Frontend CD

on:
  push:
    branches: 
    - master
    paths:
    - frontend/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: frontend cd
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          # Print commands that were run and exit with failure if error happens
          set -ex
          home="/home/ubuntu/FunctionalVote"
          # Revert any modified files and get new updates
          cd $home
          git reset --hard
          git pull

          ### FRONTEND ###
          # Build frontend files in production
          cd $home/frontend
          
          # Install packages if needed
          npm install
          
          # Build in production mode
          npm run build
