# This is a basic workflow to help you get started with Actions

name: SSH CD

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: ssh deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          home="/home/ubuntu/FunctionalVote"
          
          # Get new updates
          cd $home
          git pull

          ### BACKEND ###
          # Kill backend
          pm2 stop phoenix_dev
          # Run database migrations
          cd $home/backend
          mix ecto.migrate
          # Start backend
          pm2 start phoenix_dev

          ### FRONTEND ###
          # Build frontend files in production
          cd $home/frontend
          # Install packages if needed
          npm install
          # Build in production mode
          npm run build
